Araba Takip/Controllers/AractanimlamaController.cs
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramwork;
using EntityLayer.Concrete;

namespace Araba_Takip.Controllers
{
    public class AractanimlamaController : Controller
    {
        // GET: Aractanimlama

        AracTaManager aracm = new AracTaManager(new EfAractaDal());
        public ActionResult Aractanimla()
        {
            var degerler = aracm.GetList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult IslemEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult IslemEkle(AracTanimlama p)
        {
            aracm.AractaAdd(p);
            return RedirectToAction("Aractanimla");
        }
        public ActionResult IslemDelete(int id)
        {
            var aractaIslem = aracm.GetById(id);
            aracm.IslemDelete(aractaIslem);
            return RedirectToAction("Aractanimla");
        }
        [HttpGet]
        public ActionResult IslemUpdate(int id)
        {
            var aracIslem = aracm.GetById(id);
            return View(aracIslem);
        }
        [HttpPost]
        public ActionResult IslemUpdate(AracTanimlama p)
        {
            aracm.IslemtaUpdate(p);
            return RedirectToAction("Aractanimla");
        }
    }
}

Araba Takip/Controllers/AracıslemleriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramwork;
using EntityLayer.Concrete;
using FluentValidation.Results;

namespace Araba_Takip.Controllers
{
    public class AracıslemleriController : Controller
    {
        // GET: Aracıslemleri

        AracIsManager arm = new AracIsManager(new EfAracisDal());
        AracTaManager aracm = new AracTaManager(new EfAractaDal());

        public ActionResult AracIslemleri()
        {
            var aracList = arm.GetList();
            return View(aracList);
        }

        [HttpGet]
        public ActionResult IslemEkle()
        {
            List<SelectListItem> valueId = (from x in aracm.GetList()
                                            select new SelectListItem
                                            {
                                                Text = x.Arac_Plakasi,
                                                Value = x.AracId.ToString()
                                            }).ToList() ;
            ViewBag.vlc = valueId;
            return View();
        }
        [HttpPost]
        public ActionResult IslemEkle(AracIslemleri p)
        {
            //plaka zorunluluğu getiriyor.
            AracısValidator aracısValidator = new AracısValidator();
            ValidationResult result = aracısValidator.Validate(p);
            if (result.IsValid)
            {
                arm.AracısAdd(p);
                return RedirectToAction("AracIslemleri");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult IslemDelete(int id)
        {
            var aracIslem = arm.GetById(id);
            arm.IslemDelete(aracIslem);
            return RedirectToAction("AracIslemleri");
        }
        [HttpGet]
        public ActionResult IslemUpdate(int id)
        {
            var aracIslem = arm.GetById(id);
            return View(aracIslem);
        }
        [HttpPost]
        public ActionResult IslemUpdate(AracIslemleri p)
        {
            arm.IslemUpdate(p);
            return RedirectToAction("AracIslemleri");
        }
    }
}

Araba Takip/Controllers/BakimonarimController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramwork;
using EntityLayer.Concrete;

namespace Araba_Takip.Controllers
{
    public class BakimonarimController : Controller
    {
        // GET: Bakimonarim


        BakimManager bam = new BakimManager(new EfBakimDal());
        AracTaManager aracm = new AracTaManager(new EfAractaDal());
        public ActionResult Bakim()
        {
            var degerler = bam.GetList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult BakimEkle()
        {
            List<SelectListItem> valueId = (from x in aracm.GetList()
                                            select new SelectListItem
                                            {
                                                Text = x.Arac_Plakasi,
                                                Value = x.AracId.ToString()
                                            }).ToList();
            ViewBag.vlc = valueId;
            return View();
        }
        [HttpPost]
        public ActionResult BakimEkle(BakimOnarim p)
        {
            bam.BakimAdd(p);
            return RedirectToAction("Bakim");
        }
        public ActionResult BakimDelete(int id)
        {
            var bakim = bam.GetById(id);
            bam.BakimDelete(bakim);
            return RedirectToAction("Bakim");
        }
        [HttpGet]
        public ActionResult BakimUpdate(int id)
        {
            var bakim = bam.GetById(id);
            return View(bakim);
        }
        [HttpPost]
        public ActionResult BakimUpdate(BakimOnarim p)
        {
            bam.BakimUpdate(p);
            return RedirectToAction("Bakim");
        }


        public ActionResult JBakimEkle(BakimOnarim p)
        {
            bam.BakimAdd(p);
            return RedirectToAction("Bakim");
        }
    }
}

Araba Takip/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Araba_Takip.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
    }
}

Araba Takip/Controllers/SurucuController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramwork;
using EntityLayer.Concrete;

namespace Araba_Takip.Controllers
{
    public class SurucuController : Controller
    {
        // GET: Surucu
        SurucuManager surum = new SurucuManager(new EfSurucuDal());
        AracTaManager aracm = new AracTaManager(new EfAractaDal());
        public ActionResult Surucu()
        {
            var degerler = surum.GetList();
            return View(degerler);
        }
        
        [HttpGet]
        public ActionResult SurucuEkle()
        {
            List<SelectListItem> valueId = (from x in aracm.GetList()
                                            select new SelectListItem
                                            {
                                                Text = x.Arac_Plakasi,
                                                Value = x.AracId.ToString()
                                            }).ToList();
            ViewBag.vlc = valueId;
            return View();
        }
        [HttpPost]
        public ActionResult SurucuEkle(SurucuDetay p)
        {
            surum.SurucuAdd(p);
            return RedirectToAction("Surucu");
        }
        public ActionResult SurucuDelete(int id)
        {
            var surucuDel = surum.GetById(id);
            surum.SurucuDelete(surucuDel);
            return RedirectToAction("Surucu");
        }
        [HttpGet]
        public ActionResult SurucuUpdate(int id)
        {
            var surucu = surum.GetById(id);
            return View(surucu);
        }
        [HttpPost]
        public ActionResult SurucuUpdate(SurucuDetay p)
        {
            surum.SurucuUpdate(p);
            return RedirectToAction("Surucu");
        }
    }
}

Araba Takip/Views/Aractanimlama/Aractanimla.cshtml
@using EntityLayer.Concrete
@model List<AracTanimlama>
@{
    ViewBag.Title = "Aractanimla";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<html>
<head>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
</head>
<body>
    <br />
    <h2>Araç Tanımlama</h2>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <table id="example" class="table table-striped" style="width:100%">

        <thead>
            <tr>
                <th>Araç ID</th>
                <th>Arac Plakası</th>
                <th>Fİrma Araç No</th>
                <th>Araç Markası</th>
                <th>Araç Modeli</th>
                <th>Model Yılı</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.AracId</th>
                    <td>@item.Arac_Plakasi</td>
                    <td>@item.Firma_arac_no</td>
                    <td>@item.Arac_markasi</td>
                    <td>@item.Arac_modeli</td>
                    <td>@item.Model_yili</td>
                    <td><a href="/Aractanimlama/IslemDelete/@item.AracId" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Aractanimlama/IslemUpdate/@item.AracId" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
        </tbody>

    </table>
    <a href="/Aractanimlama/IslemEkle/" class="btn btn-primary">İşlem Ekle</a>
</body>
</html>

Araba Takip/Views/Aractanimlama/IslemEkle.cshtml
@model EntityLayer.Concrete.AracTanimlama
@{
    ViewBag.Title = "IslemEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using (Html.BeginForm("IslemEkle", "Aractanimlama", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Araç Plakası")
        @Html.TextBoxFor(x => x.Arac_Plakasi, new { @class = "form-control" })
        <br />
        @Html.Label("Firma Araç No")
        @Html.TextBoxFor(x => x.Firma_arac_no, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Markası")
        @Html.TextBoxFor(x => x.Arac_markasi, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Modeli")
        @Html.TextBoxFor(x => x.Arac_modeli, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Model Yılı")
        @Html.TextBoxFor(x => x.Model_yili, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

Araba Takip/Views/Aractanimlama/IslemUpdate.cshtml
@model EntityLayer.Concrete.AracTanimlama
@{
    ViewBag.Title = "IslemUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("IslemUpdate", "Aractanimlama", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Araç Id")
        @Html.TextBoxFor(x => x.AracId, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Plakası")
        @Html.TextBoxFor(x => x.Arac_Plakasi, new { @class = "form-control" })
        <br />
        @Html.Label("Firma Araç No")
        @Html.TextBoxFor(x => x.Firma_arac_no, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Markası")
        @Html.TextBoxFor(x => x.Arac_markasi, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Modeli")
        @Html.TextBoxFor(x => x.Arac_modeli, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Model Yılı")
        @Html.TextBoxFor(x => x.Model_yili, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Güncelle</button>
    </div>
}

Araba Takip/Views/Aracıslemleri/AracIslemleri.cshtml
@using EntityLayer.Concrete
@model List<AracIslemleri>
@{
    ViewBag.Title = "AracIslemleri";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Content/sweetalert.min.js"></script>
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<html>
<head>
    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
</head>
<body>
    <br />
    <h2>Araç İşlemleri yapildi</h2>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/dataTables.bootstrap5.min.css" rel="stylesheet" />
    <table id="example" class="table table-striped" style="width:100%">
        <thead>
            <tr>

                <th>Araç  Plakası</th>
                <th>Sigorta İşlemleri</th>
                <th>Ceza İşlemleri</th>
                <th>Kaza İşlemleri</th>
                <th>Araç Muayeneleri</th>
                <th>OGS HGS İşlemleri</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>

                    <th>@item.AracTanimlama.Arac_Plakasi</th>
                    <td>@item.Sigorta_islemleri</td>
                    <td>@item.Ceza_islemleri</td>
                    <td>@item.Kaza_islemleri</td>
                    <td>@item.Arac_muayeneleri</td>
                    <td>@item.OGS_HGS_giderleri</td>
                    <td><button class="btn btn-danger" onclick="deletee(@item.Arac_isId)">Sil</button></td>
                    <td><a href="/Aracıslemleri/IslemUpdate/@item.Arac_isId" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Aracıslemleri/IslemEkle/" class="btn btn-primary">İşlem Ekle</a>
</body>
</html>
<script>
    function deletee(id) {
        swal({
            title: "Are you sure?" + id,
            text: "Once deleted, you will not be able to recover this imaginary file!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {

                if (willDelete) {
                    $.ajax{
                        url: "../AracIslemleri/IslemDelete/",
                            type: 'POST',
                            data: { id: id },
                        datatype:'Json',
                        swal("Poof! Your imaginary file has been deleted!", {
                            icon: "success",

                        });
                    }
                } else {
                    swal("Your imaginary file is safe!");
                };


            });
    }
</script>

@*<a href="/Aracıslemleri/IslemDelete/@item.Arac_isId"*@

Araba Takip/Views/Aracıslemleri/IslemEkle.cshtml
@model EntityLayer.Concrete.AracIslemleri
@{
    ViewBag.Title = "IslemEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@using (Html.BeginForm("IslemEkle", "Aracıslemleri", FormMethod.Post))  
{
<div class="form-group">
    <br />
    @Html.Label("Araç Id")
    @Html.DropDownListFor(x => x.AracId,(List<SelectListItem>)ViewBag.vlc,new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.AracId)
    <br />
    @Html.Label("Sigorta İşlemleri")
    @Html.TextBoxFor(x => x.Sigorta_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Ceza İşlemleri")
    @Html.TextBoxFor(x => x.Ceza_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Kaza İşlemleri")
    @Html.TextBoxFor(x => x.Kaza_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Araç Muayeneleri")
    @Html.TextBoxFor(x => x.Arac_muayeneleri, new { @class = "form-control" })
    <br />
    @Html.Label("OGS HGS İşlemleri")
    @Html.TextBoxFor(x => x.OGS_HGS_giderleri, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

Araba Takip/Views/Aracıslemleri/IslemUpdate.cshtml
@model EntityLayer.Concrete.AracIslemleri
@{
    ViewBag.Title = "IslemUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("IslemUpdate", "Aracıslemleri", FormMethod.Post))
{
<div class="form-group">
    <br />

    @Html.Label("Id")
    @Html.TextBoxFor(x => x.Arac_isId, new { @class = "form-control" })
    <br />
    @Html.Label("Araç Plakası")
    @Html.TextBoxFor(x => x.AracId, new { @readonly = "readonly", @class = "form-control" })
    <br />
    @Html.Label("Sigorta İşlemleri")
    @Html.TextBoxFor(x => x.Sigorta_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Ceza İşlemleri")
    @Html.TextBoxFor(x => x.Ceza_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Kaza İşlemleri")
    @Html.TextBoxFor(x => x.Kaza_islemleri, new { @class = "form-control" })
    <br />
    @Html.Label("Araç Muayeneleri")
    @Html.TextBoxFor(x => x.Arac_muayeneleri, new { @class = "form-control" })
    <br />
    @Html.Label("OGS HGS İşlemleri")
    @Html.TextBoxFor(x => x.OGS_HGS_giderleri, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Güncelle</button>
</div>
}

Araba Takip/Views/Bakimonarim/Bakim.cshtml
@using EntityLayer.Concrete
@model List<BakimOnarim>
@{
    ViewBag.Title = "Bakim";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/dataTables.bootstrap4.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.5.1.js"></script>

<html>
<head>


</head>
<body>
    <br />
    <h2>Bakım ve Onarım</h2>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <table id="tblBakim" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Bakım ID</th>
                <th>Arac Plakası</th>
                <th>Bakım Tarihi</th>
                <th>Bakım KMsi</th>
                <th>Tutar</th>
                <th>Firma Servis</th>
                <th>Açıklamalar</th>
                <th>Sil</th>
                <th>Güncelle</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <th>@item.Bakim_Id</th>
                    <th>@item.AracTanimlama.Arac_Plakasi</th>
                    <td>@item.Bakim_tarihi</td>
                    <td>@item.Bakim_KMsi</td>
                    <td>@item.Tutar</td>
                    <td>@item.Firma_servis</td>
                    <td>@item.Aciklamalar</td>
                    <td><a href="/Bakimonarim/BakimDelete/@item.Bakim_Id" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Bakimonarim/BakimUpdate/@item.Bakim_Id" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
        </tbody>
    </table>
    <a href="/Bakimonarim/BakimEkle/" class="btn btn-primary">Bakım Ekle</a>

    <!-- Button trigger modal -->
    <button id="deneme" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" onclick="myFunction()">
        Bakım Ekle
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Bakım Ekle</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table id="example" class="table table-striped" style="width:100%">
                        <tr>
                            <td>Arac Plakası</td>
                            <td><input type="text" id="txtPlaka" /></td>
                        </tr>
                        <tr>
                            <td>Bakım Tarihi</td>
                            <td><input type="text" id="txtTarih" /></td>
                        </tr>
                        <tr>
                            <td>Bakım KMsi</td>
                            <td><input type="text" id="txtKm" /></td>
                        </tr>
                        <tr>
                            <td>Tutar</td>
                            <td><input type="text" id="txtTutar" /></td>
                        </tr>
                        <tr>
                            <td>Firma Servis</td>
                            <td><input type="text" id="txtServis" /></td>
                        </tr>
                        <tr>
                            <td>Açıklamalar</td>
                            <td><input type="text" id="txtAciklama" /></td>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnInsert" onclick="SaveBakim()">Save</button>
                </div>
            </div>
        </div>
    </div>

</body>
</html>


<script>
    //$(document).ready(function () {
    //    $('#example').DataTable();
    //});
    function SaveBakim() {

        var stoks = {
            Arac_Plakasi: $('#txtPlaka').val(),
            Bakim_tarihi: $('#txtTarih').val(),
            Bakim_KMsi: $('#txtKm').val(),
            Tutar: $('#txtTutar').val(),
            Firma_servis: $('#txtServis').val(),
            Aciklamalar: $('#txtAciklama').val()
        };
        console.log(stoks);
        var jsonData = JSON.stringify({
            stoks: stoks
        });
       
        $.ajax({
            type: "POST",
            url: '../Bakimonarim/BakimEkle',
            dataType: "json",
            data: jsonData,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                $('#txtPlaka').val("");
                $('#txtTarih').val("");
                $('#txtKm').val("");
                $('#txtTutar').val("");
                $('#txtServis').val("");
                $('#txtAciklama').val("");
            },
            error: function () {
                alert("Eksik bilgi")
            }

        });
    }

    function myFunction() {

        document.getElementById("exampleModalLabel").textContent = "butona tıklandı";


    }



</script>

Araba Takip/Views/Bakimonarim/BakimEkle.cshtml
@model EntityLayer.Concrete.BakimOnarim
@{
    ViewBag.Title = "BakimEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("BakimEkle", "Bakimonarim", FormMethod.Post))
{
<div class="form-group">
    <br />
    @Html.Label("Araç Plakası")
    @Html.DropDownListFor(x => x.AracId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    @Html.Label("Bakım Tarihi ")
    @Html.TextBoxFor(x => x.Bakim_tarihi, new { @class = "form-control" })
    <br />
    @Html.Label("Bakım KMsi")
    @Html.TextBoxFor(x => x.Bakim_KMsi, new { @class = "form-control" })
    <br />
    @Html.Label("Tutar")
    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
    <br />
    @Html.Label("Firma Servis")
    @Html.TextBoxFor(x => x.Firma_servis, new { @class = "form-control" })
    <br />
    @Html.Label("Açıklamalar")
    @Html.TextBoxFor(x => x.Aciklamalar, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</div>
}

Araba Takip/Views/Bakimonarim/BakimUpdate.cshtml
@model EntityLayer.Concrete.BakimOnarim
@{
    ViewBag.Title = "BakimUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("BakimUpdate", "Bakimonarim", FormMethod.Post))
{
    <div class="form-group">
        <br />
        @Html.Label("Bakım ID")
        @Html.TextBoxFor(x => x.Bakim_Id, new { @class = "form-control" })
        <br />
        @Html.Label("Araç Plakası")
        @Html.TextBoxFor(x => x.AracId, new { @readonly = "readonly", @class = "form-control" })
        <br />
        @Html.Label("Bakım Tarihi ")
        @Html.TextBoxFor(x => x.Bakim_tarihi, new { @class = "form-control" })
        <br />
        @Html.Label("Bakım KMsi")
        @Html.TextBoxFor(x => x.Bakim_KMsi, new { @class = "form-control" })
        <br />
        @Html.Label("Tutar")
        @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
        <br />
        @Html.Label("Firma Servis")
        @Html.TextBoxFor(x => x.Firma_servis, new { @class = "form-control" })
        <br />
        @Html.Label("Açıklamalar")
        @Html.TextBoxFor(x => x.Aciklamalar, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Güncelle</button>
    </div>
}

Araba Takip/Views/Bakimonarim/BakimonarimModalPartial.cshtml
@using EntityLayer.Concrete
@model BakimOnarim


<div class="modal fade" id="addBakim">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            </div> 
            <form action="Create">
                <div class="form-group">
                    <br />
                    @Html.Label("Bakım ID")
                    @Html.TextBoxFor(x => x.Bakim_Id, new { @class = "form-control" })
                    <br />
                    @Html.Label("Araç Plakası")
                    @Html.TextBoxFor(x => x.AracId, new { @readonly = "readonly", @class = "form-control" })
                    <br />
                    @Html.Label("Bakım Tarihi ")
                    @Html.TextBoxFor(x => x.Bakim_tarihi, new { @class = "form-control" })
                    <br />
                    @Html.Label("Bakım KMsi")
                    @Html.TextBoxFor(x => x.Bakim_KMsi, new { @class = "form-control" })
                    <br />
                    @Html.Label("Tutar")
                    @Html.TextBoxFor(x => x.Tutar, new { @class = "form-control" })
                    <br />
                    @Html.Label("Firma Servis")
                    @Html.TextBoxFor(x => x.Firma_servis, new { @class = "form-control" })
                    <br />
                    @Html.Label("Açıklamalar")
                    @Html.TextBoxFor(x => x.Aciklamalar, new { @class = "form-control" })
                    <br />
                    <button class="btn btn-info">Güncelle</button>
                </div>
            </form>
        </div>
    </div>
</div>

Araba Takip/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Layout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>